export class CONSTANT {
     public static readonly DESCRIPTION_PART = "Описание на част";
     public static readonly DESCRIPTION_CAR = "Допълнителна информация";
     public static readonly REFERNCE_CAR = "Избери кола"; 
     public static readonly COMPANY = "Марка";
     public static readonly MODEL = "Модел";
     public static readonly GENERATION = "Генерация";
     public static readonly MODIFICATION = "Модификация";
     public static readonly POWERKWH = "Мощност (kWh)"
     public static readonly POWERBHP = "Мощност (k.c)"
     public static readonly VIN = "VIN"
     public static readonly TYPE_ENGINE = "Двигател";
     public static readonly CODE_ENGINE = "Kод двигател";
     public static readonly TYPE_GEARBOX = "Скоростна кутия";
     public static readonly PRICE = "Цена";
     public static readonly YEAR = "Година";
     public static readonly CAR = "Кола";
     public static readonly BUS = "Бус";
     public static readonly PART = "Част";
     public static readonly CATEGORY = "Категория";
     public static readonly SUBCATEGORY = "Подкатегория";
     public static readonly DEALERSUBCATEGORY = "Дилър Подкатегория";
     public static readonly CAR_DETAILS = "Детайли на колат";
     public static readonly PART_DETAILS = "Детайли за частта";
     public static readonly PART_NUMBER = "Номер на част";
     public static readonly KWH_TO_BHP = 1.36
     public static readonly PART_FOR_CAR = "Част за кола"
     public static readonly PART_FOR_BUS = "Част за бус"
     public static readonly PART_ONLY = "Само части"
     public static readonly POSITION = "Позиция"
     public static readonly MILLAGE = "Пробег"
     public static readonly REGION = "Регион";
     public static readonly VIEW = "Разгледай"
     public static readonly GOBACK = "Назад"
     public static readonly GOHOME = "Начало"
     public static readonly KEYWORDS = "Търси"
     public static readonly CURRENCY = "лв."
     public static readonly CLEARFILTER = "Изчисти"
     public static readonly EXTENDED_SERARCH = "Разширено търсене"
     public static readonly MINIMUM_SERARCH = "Минимално търсене"
     public static readonly SEARCHING = "Tърсене";
     public static readonly DISPLAY_FILTER = "Покажи филтър";
     public static readonly HIDE_FILTER = "Скрий филтър";
     public static readonly KEYWORD = "Ключова дума"
     public static readonly TOSEARCH = "Промени филтъра"
     public static readonly TORESULT = "Към резултатите"
     public static readonly YEAR_FROM = "Година от"
     public static readonly YEAR_TO = "Година до"
     public static readonly KUPE = "Купе"
    // Actions
     public static readonly SEARCH = "Tърси";
     public static readonly SEARCH_BY_PART = "Tърси по номер на частта";
     public static readonly UPDATE = "Промени";
     public static readonly REMOVE = "Премахни";
     public static readonly SAVE = "Запиши";
     public static readonly DELETE = "Изтрий";
     public static readonly NEW = "Нов";
     public static readonly ADD = "Добави";
     public static readonly PUBLISH = "Рекламирай"
     public static readonly BUY = "Купи"
     public static readonly UPLOAD = "Качи снимка"
     public static readonly CHECKOUT = "Кошница"
    
     public static readonly NO_MATER   = "Без значение";
     public static readonly LEFT       = "Лявa";
     public static readonly RIGHT      = "Дяснa";
     public static readonly FRONT      = "Преднa";
     public static readonly BACK       = "Заднa";
     public static readonly NEWID      = 1000000;
    
     public static readonly YEAR_START = 1970
    // User
    
     public static readonly CANCEL = "Отмени"
     public static readonly COMPANYNAME = "Фирма";
     public static readonly FIRSTNAME = "Име";
     public static readonly FATHERNAME = "Бащино";
     public static readonly LASTNAME = "Фамилия";
     public static readonly EMAIL = "Е-майл";
     public static readonly PHONE = "Мобилен";
     public static readonly PHONE2 = "Мобилен 2";
     public static readonly VIBER = "Viber";
     public static readonly STREET = "Улица";
     public static readonly STREETNUMBER = "Номер";
     public static readonly FLOOR = "Етаж";
     public static readonly APPARTMENT = "Апартамент";
     public static readonly CITY = "Населено място";
     public static readonly COUNTY = "Община";
     public static readonly LOGINNAME = "Потребителско име/Е-майл/Телефон"
     public static readonly REGNAME = "Потребителско име/Телефон"
     public static readonly USERNAME = "Потребителско име";
     public static readonly SELECTTYPEAD = "Вид обява";
     public static readonly APPROVEAD = "Одобрена";
     public static readonly CATCHA = "Код"
     public static readonly PASSWORD = "Парола";
     public static readonly PASSWORD2 = "Подвърди Парола";
     public static readonly OLDPASSWORD = "Стара Парола";
     public static readonly SECURITYQUESTION = "Подсказваща дума";
     public static readonly QUESTION = "Подсказваща дума";
     public static readonly UPDATEPASSWORD = "Промяна на парола";
     public static readonly DETAILS = "Детайли";
     public static readonly PASSWОRDNOTSAME = "Потвърдената парола е различна";
     public static readonly NUMBERPARTS = "Общ брой на части: "
     public static readonly ONLYPARTS = "Само части";
     public static readonly WITHIMAGES = "Със снимки";
     public static readonly USER = "Потребител";
     public static readonly NAME = "Вашето име"
     public static readonly DEALER = "Дилър";
     public static readonly MODIFIEDTIME = "Публикувана"
     public static readonly WEBPAGE = "Уеб страница";
     public static readonly USERNAMEREQUIRED = "Моля въведете потребителското име"
     public static readonly REGIONREQUIRED = "Моля Избери регион"
     public static readonly PASSWORDREQUIRED = "Моля въведете парола"
     public static readonly PHONEREQUIRED= "Моля въведете валиден мобилен телефон"
     public static readonly EMAILREQUIRED = "Моля въведете Вашият е-майл"
     public static readonly PASSWORDNOTTHESAMEREQUIRED = "Потвърждаващата парола не съвпада"
     public static readonly PARTCOUNTS = "Брой части"
     public static readonly SHOWPARTS = "Покажи части"
     public static readonly HIDEPARTS = "Скрий части"
     public static readonly ADMINISTRATION = "Администрация"
     public static readonly ADDCATEGORY = " Добави Категория"
     public static readonly ADDSUBCATEGORY = " Добави Подкатегория"
     public static readonly ADDDEALESUBCATEGORY = " Добави Дилър Подкатегория"
     public static readonly ADDCOMPANY = " Добави Марка"
     public static readonly ADDMODEL = " Добави Модел"
     public static readonly ADDMODIFICATION = " Добави Модификация"
     public static readonly USERS = "Потребители"
     public static readonly DEALERSUBCATEGORYNAME = "Дилър Подкатегория Име"
     public static readonly DESCRIPTION = "Описание"
     public static readonly CAR_SELL = " Коли на части"
     public static readonly BUS_SELL = " Бус на части"
     public static readonly OTHERS = "Други"
     public static readonly RECOVERPASSWORD = "Възстанови парола"
     public static readonly SAVED = "Запазени"
     public static readonly SALER = "Продавач"
     public static readonly FIRST = "Основна"
     public static readonly SORTBY = "Сортирай"
     public static readonly ALL = " Всички"
     public static readonly USERFOUND = "USERFOUND"
     public static readonly USERALREADYEXIST = "Потребител с такова име/е-майл/телефон вече същестува!"
     public static readonly WARNING = "Съобщение"
     public static readonly USERNOTACTIVATED = "Потребителя не е активиран."
     public static readonly USERBLOCKED = "Потребителя е блокиран."
     public static readonly ACTIVATEUSER = "Искате ли да активирате потребител?"
     public static readonly ADDRESS_TITLE = "Адрес"
     public static readonly DEALERSUBCATEGORYHELP = "Определение на частта"
     public static readonly MESSAGE = "Съобщение"
     public static readonly ADDRESS = "Въведете адрес"
     public static readonly DESCRIPTIONCOMPANY = "Въведете описани на компанията"
     public static readonly REQUEST = "Запитване към продавача"
     public static readonly RESULT = "Към търсенето"
     public static readonly RECOVERYUSER = "Линк до Вашият е-майл е изпратен с Вашият акаунт!"
     public static readonly INFO = "Информация"
     public static readonly NORESULTS = "Няма обяви за вашият филтър"
     public static readonly ERROR = "Грешка"
    
     public static readonly TYRE = "Гума";
     public static readonly TYRE_PRODUCER = "Марка на гумата";
     public static readonly TYRE_WIDTH = "Широчина";
     public static readonly TYRE_HEIGHT = "Височина";
     public static readonly TYRE_RADIUS = "Диаметър";
     public static readonly TYRE_TYPE = "Сезонност";
     public static readonly LOGOUT = "Изход";
    
     public static readonly CHANGEPASSWORD = "Промени парола"
     public static readonly RECOVERYACCOUNT = "Възстановяване на акаунт";
     public static readonly RECOVERYALREADYACTIVATED = "Този акаунт е вече активиран"
     public static readonly RECOVERYMESSAGE = "Потр. име, телефон или е-майл"
     public static readonly WHATS = "Whats";
}
