CREATE TABLE [dbo].[RimWithTyre]
(
	[rimWithTyreId] BIGINT NOT NULL PRIMARY KEY,
    [itemType] INT NOT NULL DEFAULT 0,
    [tyreCompanyId] INT NOT NULL DEFAULT 0, 
    [tyreWidth] INT NOT NULL DEFAULT 0, 
    [tyreHeight] INT NOT NULL DEFAULT 0, 
    [tyreRadius] INT NOT NULL DEFAULT 0, 
    [tyreType] INT NOT NULL DEFAULT 0, 
    [rimWidth] INT NOT NULL DEFAULT 0,    
    [companyId] INT NOT NULL DEFAULT 0,
    [modelId] INT NOT NULL DEFAULT 0,
    [rimMaterial]  INT NOT NULL DEFAULT 0,
    [rimOffset] INT NOT NULL DEFAULT 0,
    [rimBoltCount] INT NOT NULL DEFAULT 0,
    [rimBoltDistance] INT NOT NULL DEFAULT 0,
    [rimCenter] INT NOT NULL DEFAULT 0,
    [price] DECIMAL NOT NULL DEFAULT 0, 
    [description] NVARCHAR(500) NOT NULL DEFAULT '', 
    [mainImageId] INT NOT NULL DEFAULT 0,
    [mainPicture] NVARCHAR(200) NOT NULL DEFAULT '', 
    [regionId] INT NOT NULL DEFAULT 0, 
    [userId] INT NOT NULL DEFAULT 0, 
    [approved] INT NOT NULL DEFAULT 0, 
    [createdTime] BIGINT NOT NULL DEFAULT 0, 
    [modifiedTime] BIGINT NOT NULL DEFAULT 0,
    [deleted] INT NOT NULL DEFAULT 0, 
    [count] INT NOT NULL DEFAULT 0, 
    [month] INT NOT NULL DEFAULT 0, 
    [year] INT NOT NULL DEFAULT 0
)
