CREATE TABLE [dbo].[User]
(
	[userId] INT IDENTITY(1,1) PRIMARY KEY, 
    [companyName] NVARCHAR(50) NOT NULL DEFAULT '', 
    [firstName] NVARCHAR(50) NOT NULL DEFAULT '', 
    [fatherName] NVARCHAR(50) NOT NULL DEFAULT '', 
    [lastName] NVARCHAR(50) NOT NULL DEFAULT '', 
    [phone] NVARCHAR(50) NOT NULL DEFAULT '', 
    [phone2] NVARCHAR(50) NOT NULL DEFAULT '', 
    [viber] NVARCHAR(50) NOT NULL DEFAULT '', 
    [whats] NVARCHAR(50) NOT NULL DEFAULT '', 
    [email] NVARCHAR(100) NOT NULL DEFAULT '', 
    [address] NVARCHAR(100) NOT NULL DEFAULT '', 
    [city] NVARCHAR(50) NOT NULL DEFAULT '', 
    [userName] NVARCHAR(50) NOT NULL DEFAULT '',  
    [password] NVARCHAR(256) NOT NULL DEFAULT '', 
    [dealer] INT NOT NULL DEFAULT 0, 
    [blocked] INT NOT NULL DEFAULT 0, 
    [blockedDate] DATETIME NOT NULL DEFAULT 0, 
    [creationDate] DATETIME NOT NULL DEFAULT 0, 
    [regionId] INT NOT NULL DEFAULT 0, 
    [webPage] NVARCHAR(100) NOT NULL DEFAULT '', 
    [activationCode] NVARCHAR(60) NOT NULL DEFAULT '', 
    [attempt] INT NOT NULL DEFAULT 0, 
    [activated] SMALLINT NOT NULL DEFAULT 0, 
    [description] NVARCHAR(250) NOT NULL DEFAULT '', 
    [imageId] INT NOT NULL DEFAULT 0, 
    [deleted] INT NOT NULL DEFAULT 0, 
    [deleteDateTime] datetime NOT NULL DEFAULT 0, 
    [suspended] INT NOT NULL DEFAULT 0, 
    [suspendedDateTime] BIGINT NOT NULL DEFAULT 0
)
