CREATE PROCEDURE dbo.FilterPartIns
	@filterId BIGINT, 
    @itemType INT,
	@carId BIGINT, 
    @companyId BIGINT, 
    @modelId INT,
    @modificationId INT,
    @year INT,
    @categoryId INT,
    @categoriesId NVARCHAR(150),
    @subCategoryId INT,
    @subCategoriesId NVARCHAR(150),
    @engineType INT,
    @engineModel NVARCHAR(75),
    @partNumber NVARCHAR(75),
    @powerkWh INT,
    @powerBHP INT,
    @gearboxType INT,
    @categories NVARCHAR(150),
    @partOnly INT,
    @searchBy SMALLINT,
    @regNumber NVARCHAR(50),
    @extendedSearch SMALLINT,
    
    @tyreCompanyId INT,
    @tyreWidth INT,
    @tyreHeight INT,
    @tyreRadius INT,
    @tyreType INT,
    @rimCompanyId INT,
    @rimModelId INT,
    @rimWidth INT,
    @rimMaterial INT,
    @rimOffset INT,
    @rimBoltCount INT,
    @rimBoltDistance INT,
    @rimCenter INT,

    @clientId BIGINT,
    @userId INT,
    @loadMainPicture SMALLINT,
    @orderBy SMALLINT,
    @regionId INT,
    @hasImages INT,
    @keyword NVARCHAR(150),
    @description NVARCHAR(150),
    @adminRun INT,
    @approved INT,
    @bus INT,
    @partForCar INT,
    @modelsId NVARCHAR(MAX),
    @modificationsId NVARCHAR(MAX)
AS
	INSERT INTO FilterPart 
    (
        
        filterId, 
        itemType,
        carId, 
        companyId, 
        modelId,
        modificationId,
        [year],
        categoryId,
        categoriesId,
        subCategoryId,
        subCategoriesId,
        engineType,
        engineModel,
        partNumber,
        powerkWh,
        powerBHP,
        gearboxType,
        categories,
        partOnly,
        searchBy,
        regNumber,
        extendedSearch,
        tyreCompanyId,
        tyreWidth,
        tyreHeight,
        tyreRadius,
        tyreType,
        rimCompanyId,
        rimModelId,
        rimWidth,
        rimMaterial,
        rimOffset,
        rimBoltCount,
        rimBoltDistance,
        rimCenter,
        clientId,
        userId,
        loadMainPicture,
        orderBy,
        regionId,
        hasImages,
        keyword,
        [description],
        adminRun,
        approved,
        bus,
        partForCar,
        modelsId,
        modificationsId
     )
        VALUES 
     (
        @filterId, 
        @itemType,
        @carId, 
        @companyId, 
        @modelId,
        @modificationId,
        @year,
        @categoryId,
        ISNULL(@categoriesId,''),
        @subCategoryId,
        ISNULL(@subCategoriesId,''),
        @engineType,
        @engineModel,
        @partNumber,
        @powerkWh,
        @powerBHP,
        @gearboxType,
        @categories,
        @partOnly,
        @searchBy,
        @regNumber,
        @extendedSearch,
        @tyreCompanyId,
        @tyreWidth,
        @tyreHeight,
        @tyreRadius,
        @tyreType,
        @rimCompanyId,
        @rimModelId,
        @rimWidth,
        @rimMaterial,
        @rimOffset,
        @rimBoltCount,
        @rimBoltDistance,
        @rimCenter,
        @clientId,
        @userId,
        @loadMainPicture,
        @orderBy,
        @regionId,
        @hasImages,
        @keyword,
        @description,
        @adminRun,
        @approved,
        @bus,
        @partForCar,
        @modelsId,
        @modificationsId
    )
RETURN 0
