CREATE PROCEDURE [dbo].[CarsIns]
    @carId          BIGINT,
    @modelId        INT,
    @modificationId INT,
    @year           INT,
    @vin            NVARCHAR (20),
    @regNumber      NVARCHAR (50),
    @description    NVARCHAR (100),
    @price          DECIMAL (18),
    @powerkWh       INT,
    @powerBHP       INT,
    @engineType     INT,
    @engineModel    NCHAR (10),
    @userId         INT,
    @millage         INT,
    @regionId       INT,
    @gearboxType    INT,
    @modifiedTime   BIGINT,
    @mainPicture    NVARCHAR(200),
    @mainImageId    INT,
    @approved       INT,
    @bus            INT

AS
	INSERT INTO [Cars]
    ( 
        carId,
        modelId, 
        modificationId, 
        [year],  
        vin, 
        regNumber, 
        description, 
        price, 
        powerkWh, 
        powerBHP, 
        engineType , 
        engineModel,
        userId,
        millage,
        regionId,
        gearboxType,
        createdTime,
        modifiedTime,
        mainPicture,
        mainImageId,
        deleted,
        approved,
        bus
    ) 
    VALUES (
        @carId,
        @modelId,
        @modificationId,
        @year,
        RTRIM(@vin),
        RTRIM(@regNumber),
        RTRIM(@description),
        @price,
        @powerkWh,
        @powerBHP,
        @engineType,
        RTRIM(@engineModel),
        @userId,
        @millage,
        @regionId,
        @gearboxType,
        @modifiedTime,
        @modifiedTime,
        @mainPicture,
        @mainImageId,
        0,
        @approved,
        @bus
    )

RETURN @@ROWCOUNT
