CREATE PROCEDURE [dbo].[PartsIns]
    @partId                 BIGINT,
    @carId                  BIGINT,
    @description            NVARCHAR (500),
    @partNumber             NVARCHAR (50),
    @price                  DECIMAL (18),
    @leftRightPosition      INT,
    @frontBackPosition      INT,
    @engineType             INT,
    @engineModel            NVARCHAR (50),
    @year                   INT,
    @powerkWh               INT,
    @powerBHP               INT,
    @modelId                INT,
    @modificationId         INT,
    @userId                 INT,
    @millage                 INT, 
    @regionId               INT,
    @gearboxType            INT,
    @modifiedTime           BIGINT,
    @dealerSubCategoryId    INT,
    @dealerSubCategoryName  NVARCHAR(50),
    @mainPicture            NVARCHAR(200),
    @mainImageId            INT,
    @approved               INT,
    @bus                    INT

AS


	INSERT INTO Parts 
    (
        partId, 
        carId, 
        modelId,
        modificationId,
        dealerSubCategoryId,
        description, 
        partNumber,
        price, 
        leftRightPosition, 
        frontBackPosition, 
        engineType, 
        engineModel, 
        [year], 
        powerkWh, 
        powerBHP, 
        userId,
        millage,
        regionId,
        gearboxType,
        createdTime,
        modifiedTime,
        dealerSubCategoryName,
        mainPicture,
        mainImageId,
        deleted,
        approved,
        bus,
        keyword
    ) 
    VALUES 
    (
        @partId,
        @carId,
        @modelId,
        @modificationId,
        @dealerSubCategoryId,
        RTRIM(@description),
        RTRIM(@partNumber),
        @price,
        @leftRightPosition,
        @frontBackPosition,
        @engineType,
        RTRIM(@engineModel),
        @year,
        @powerkWh,
        @powerBHP,
        @userId,
        @millage,
        @regionId,
        @gearboxType,
        @modifiedTime,
        @modifiedTime,
        @dealerSubCategoryName,
        @mainPicture,
        @mainImageId,
        0,
        @approved,
        @bus,
        LOWER(CONCAT(@partNumber, @description, @dealerSubCategoryName))
    )

RETURN @@ROWCOUNT
