CREATE PROCEDURE [dbo].[RimWithTyreIns]
	@rimWithTyreId BIGINT,
    @itemType INT,
    @tyreCompanyId INT, 
    @tyreWidth INT, 
    @tyreHeight INT, 
    @tyreRadius INT, 
    @tyreType INT, 
    @companyId INT,
    @modelId INT,
    @rimWidth INT,
    @rimMaterial INT,
    @rimOffset INT,
    @rimBoltCount INT,
    @rimBoltDistance INT,
    @rimCenter INT,
    @price DECIMAL, 
    @description NVARCHAR(500), 
    @mainImageId INT,
    @mainPicture NVARCHAR(200), 
    @regionId INT, 
    @userId INT, 
    @modifiedTime BIGINT,
    @count INT,
    @month INT,
    @year INT 
AS
	INSERT INTO RimWithTyre 
    (
	    rimWithTyreId,
        itemType,
        tyreCompanyId, 
        tyreWidth, 
        tyreHeight, 
        tyreRadius, 
        tyreType,   
        companyId,
        modelId,
        rimWidth,
        rimMaterial,
        rimOffset,
        rimBoltCount,
        rimBoltDistance,
        rimCenter,
        price, 
        [description], 
        mainImageId,
        mainPicture, 
        regionId,
        userId, 
        approved, 
        createdTime, 
        modifiedTime,
        [count],
        [month],
        [year]
    )
    VALUES
    (
	    @rimWithTyreId,
        @itemType,
        @tyreCompanyId, 
        @tyreWidth, 
        @tyreHeight, 
        @tyreRadius, 
        @tyreType,   
        @companyId,
        @modelId,
        @rimWidth,
        @rimMaterial,
        @rimOffset,
        @rimBoltCount,
        @rimBoltDistance,
        @rimCenter,
        @price, 
        @description, 
        @mainImageId,
        @mainPicture, 
        @regionId,
        @userId, 
        0, 
        @modifiedTime, 
        @modifiedTime,
        @count,
        @month,
        @year
    )
RETURN 0
