CREATE PROCEDURE [dbo].[RimWithTyreUpd]
	@rimWithTyreId BIGINT,
    @tyreCompanyId INT, 
    @tyreWidth INT, 
    @tyreHeight INT, 
    @tyreRadius INT, 
    @tyreType INT, 
    @companyId INT,
    @modelId INT,
    @rimWidth INT,
    @rimMaterial INT,
    @rimOffset INT,
    @rimBoltCount INT,
    @rimBoltDistance INT,
    @rimCenter INT,
    @price DECIMAL, 
    @description NVARCHAR(500), 
    @mainImageId INT,
    @regionId INT,
    @userId INT,
    @mainPicture NVARCHAR(200), 
    @modifiedTime BIGINT,
    @count INT,
    @month INT,
    @year INT 
AS
	UPDATE RimWithTyre 
    SET
        tyreCompanyId = @tyreCompanyId, 
        tyreWidth = @tyreWidth, 
        tyreHeight = @tyreHeight, 
        tyreRadius = @tyreRadius, 
        tyreType = @tyreType,   
        companyId = @companyId,
        modelId = @modelId,
        rimWidth = @rimWidth,
        rimMaterial = @rimMaterial,
        rimOffset = @rimOffset,
        rimBoltCount = @rimBoltCount,
        rimBoltDistance = @rimBoltDistance,
        rimCenter = @rimCenter,
        price = @price, 
        [description] = @description, 
        regionId = @regionId,
        mainImageId = @mainImageId,
        mainPicture = @mainPicture, 
        modifiedTime = @modifiedTime,
        [count] = @count,
        [month] = @month, 
        [year] = @year
	WHERE rimWithTyreId = @rimWithTyreId AND userId = @userId
RETURN 0
